- name: print msg
  hosts: all 
  tasks:
     - name: gather facts
       debug:
         msg: "Hellow World"
     - name: print facts                       ##gather facts
       debug:
         msg: "{{ansible_all_ipv4_addresses}}" 
     - name: ignore error                      ##ignore error                 
       debug: 
         msg: "{{abc.1234}}"
       ignore_errors: yes   
     - name: ignore error trial 
       yum:
         name: httpd
         state: present
       become: true
     - name: condition task 1              ##conditions
       command: sudo yum install java -y
       when: ansible_os_family == "RedHat"
     - name: task 2 (with multiple conditions)
       yum: 
         name: mariadb105-server
         state: present
       become: true
       when: 
          - ansible_distribution == "Amazon"
          - ansible_distribution_major_version == "2023"
     - name: privileges escalation                      ##privileges escalation
       command: touch /home/ec2-user/file3
       become_user: ec2-user
       become: true
     - name: print names                               ##loops
       debug:
          msg: "{{item}} Bhondave"
       loop:
          - Swapnali
          - Arti
          - Ajinkya
       
     