- name: print msg
  hosts: all 
  become: true
  tasks:
     - name: gather facts
       debug:
         msg: "Hellow World"
     - name: print facts
       debug:
         msg: "{{ansible_all_ipv4_addresses}}"
     