- name: httpd
  hosts: all
  become: true
  tasks:
    - name: install http
      yum:
        name: http
        state: latest
    - name: install docker and mariadb
      yum:
        name: {{ packages }} 
        state: latest
      vars:
        packages:
        - docker
        - mariadb105-server        