- name: install tomcat
  hosts: all
  become: true
  tasks:
     - name: install java
       yum:
         name: java
         state: present
     - name: Download file for tomcat
       get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.99/bin/apache-tomcat-8.5.99.tar.gz
        dest: /home/ec2-user/
        force_basic_auth: yes
     - name: Unarchive a tomcat file
       unarchive:
         src: /home/ec2-user/apache-tomcat-8.5.99.tar.gz
         dest: /opt/
         remote_src: yes
     - name: Download file for template
       get_url: 
        url: https://www.free-css.com/assets/files/free-css-templates/download/page296/little-fashion.zip
        dest: /opt/apache-tomcat-8.5.99/webapps/
        force_basic_auth: yes
     - name: Unarchive a template file
       unarchive:
         src: /opt/apache-tomcat-8.5.99/webapps/little-fashion.zip
         dest: /opt/apache-tomcat-8.5.99/webapps/
         remote_src: yes
     - name: Tomcat startup
       shell:
         cmd: bash /opt/apache-tomcat-8.5.99/bin/startup.sh start
     - name: install mariadb
       yum:
         name: mariadb105-server
         state: present
     - name: test mysql_secure_installation
  mysql_secure_installation:
    login_password: ''
    new_password: password22
    user: root
    login_host: localhost
    hosts: ['localhost']
    change_root_password: true
    remove_anonymous_user: true
    disallow_root_login_remotely: true
    remove_test_db: true
  register: mysql_secure
