- name: install tomcat
  hosts: all
  become: true
  tasks:
     - name: install java
       yum:
        name: java
        state: present
     - name: Download file for tomcat
       get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.99/bin/apache-tomcat-8.5.99.tar.gz
        dest: /home/ec2-user/
        force_basic_auth: yes
     - name: Unarchive a tomcat file
       unarchive:
         src: /home/ec2-user/apache-tomcat-8.5.99.tar.gz
         dest: /opt/
         remote_src: yes
     - name: Download file for template
       get_url: 
        url: https://www.free-css.com/assets/files/free-css-templates/download/page296/little-fashion.zip
        dest: /opt/apache-tomcat-8.5.99/webapps/
        force_basic_auth: yes
     - name: Unarchive a template file
       unarchive:
         src: /opt/apache-tomcat-8.5.99/webapps/little-fashion.zip
         dest: /opt/apache-tomcat-8.5.99/webapps/
         remote_src: yes
     - name: Tomcat startup
       shell:
         cmd: bash /opt/apache-tomcat-8.5.99/bin/startup.sh start
     - name: install mariadb
       yum:
         name: mariadb105-server
         state: present
     - name: Start MariaDB service
       service:
        name: mariadb
        state: started
        enabled: yes
     - name: Install python3 
       package:
        name:
           - python3-pip  
        state: present
     - name: install pip module
       pip:
        name:
          - pexpect
        state: present
     - name: install pymysql
       pip:
         name: pymysql
         state: present
     - name: Secure MariaDB installation
       expect:
         command: mysql_secure_installation
         responses:
           'Enter current password for root (enter for none):': '\r\n'
           'Set root password? [Y/n]': 'Y'
           'New password:': '12345678'
           'Re-enter new password:': '12345678'
           'Remove anonymous users? [Y/n]': 'Y'
           'Disallow root login remotely? [Y/n]': 'Y'
           'Remove test database and access to it? [Y/n]': 'Y'
           'Reload privilege tables now? [Y/n]': 'Y'
       register: mysql_secure_output
       failed_when: "'Enter current password for root (enter for none):' not in mysql_secure_output.stdout"
     - name: Create public IP address
       azure_rm_publicipaddress:
         resource_group: rg-cs-ansible
         allocation_method: Static  
         name: pip-cs-web
       register: output_ip_address

     - name: Output public IP
       debug:
          msg: "The public IP is {{ output_ip_address.state.ip_address }}"
     - name: Create database user with name 'bob' and password '12345' with all database privileges
       mysql_user:
          name: swapnali
          password: 12345678
          priv: '*.*:ALL'
          state: present
       ignore_errors: yes
       mysql_db:
         name: studentapp
         state: present
     - name: Create table
       mysql_query:
         login_user: swapnali
         login_password: 12345678
         login_db: studentapp
         query: "CREATE TABLE if not exists students(student_id INT NOT NULL AUTO_INCREMENT,
	              student_name VARCHAR(100) NOT NULL,
                student_addr VARCHAR(100) NOT NULL,
	              student_age VARCHAR(3) NOT NULL,
	              student_qual VARCHAR(20) NOT NULL,
	              student_percent VARCHAR(10) NOT NULL,
	              student_year_passed VARCHAR(10) NOT NULL,
	              PRIMARY KEY (student_id)
                );"